---
- block:
  - name: Create database
    include_role:
      name: c2platform.core.postgresql_tasks
      tasks_from: database
    vars:
      lcm_role_upgrade: keycloak
  delegate_to: "{{ keycloak_database_inventory_hostname }}"
  become_user: postgres
