---
- name: Create service
  template:
    owner: root
    group: root
    mode: 0644
    src: keycloak.service.j2
    dest: /etc/systemd/system/keycloak.service
  notify:
    - systemctl-daemon-reload
    - keycloak-systemctl-restart

- name: enable keycloak
  systemd:
    name: keycloak
    enabled: yes
